version: "3.6"

services:
  microservice-example:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app/
    ports:
      - "${DEBUG_PORT:-3001}:${DEBUG_PORT:-3001}"
      - "${SERVER_HTTP_PORT:-3000}:${SERVER_HTTP_PORT:-3000}"
    command: npm run serve:dev

  # Mongo Database
  mongo:
    image: mongo
    logging:
      driver: none
    volumes:
      - /data/db
    ports:
      - 27017:27017
